### ISSUE TITLE
Prefix not in the table?

### ISSUE THREAD

**Issue by shiro** [euank/v6plus-tun#1]
Hi, I know this project is very niche and not sure if you're still using it, so feel free to ignore this issue :D

My router is currently dying, so I was checking if I could connect through hikari with my raspberry, but I get an error when running the calculator:

```
$ cargo run calculate "2001:f70:3ac0:2800:X:X:X:X"
Error: unknown prefix: 2001:f70
```

Did they perhaps add new prefixes?

I triple checked my public IPv6 on my PC, router and http://check.xpass.jp/, which all indicate that it's `2001:f70:3ac0:2800:X:X:X:X`, any ideas what could be going on?

**Comment by euank** [comment]
Hello. I'm happy to say I'm still using this for my router ([as described here](https://euank.com/2023/02/22/v6-plus.html)) with no issues.

My guess at what's going on here is that you've got a DS-Lite ISP, not JPNE MAP-E. My setup is JPNE, and I think the DS-Lite setup is different enough this repo probably won't be of any help :sweat_smile:.

One of the blogs I referenced when setting up my router was [this one](https://vector.hateblo.jp/entry/2021/02/17/142458)

It looks like that same person also switched to a DS-Lite setup and [wrote a newer post about that](https://vector.hateblo.jp/entry/2021/06/04/222117), so their info might be useful for figuring your setup out!

Good luck!
